[package]
name = "strata-plugin"
description = "Lua plugin host for strata"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
mlua.workspace = true

[dev-dependencies]
tempfile.workspace = true
