[package]
name = "strata-sys"
description = "Disk, memory, I/O and Docker metrics for strata"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true

[dev-dependencies]
tempfile.workspace = true
